monitor.bluez.properties = {
  # High-quality audio only. Do not expose telephony (HSP/HFP) profiles.
  bluez5.roles = [ a2dp_sink a2dp_source bap_sink bap_source ]
  bluez5.codecs = [ sbc sbc_xq aac ldac aptx aptx_hd aptx_ll aptx_ll_duplex faststream faststream_duplex opus_05 opus_05_51 opus_05_71 opus_05_duplex opus_05_pro lc3 lc3_swb ]
}
