general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = wlopm --on \*
}

listener {
    timeout = 120
    on-timeout = brightnessctl -s -d tpacpi::kbd_backlight set 0
    on-resume = brightnessctl -r -d tpacpi::kbd_backlight
}

listener {
    timeout = 120
    on-timeout = loginctl lock-session
}

listener {
    timeout = 180
    on-timeout = wlopm --off \*
    on-resume = wlopm --on \*
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
}
